/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import codigo.Archivo;
import codigo.RSA;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.security.PrivateKey;
import java.security.PublicKey;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author user1
 */
public class Ventana extends javax.swing.JFrame {
    private PrivateKey llavePrivada;
    private PublicKey llavePublica;
    private String rutaLlavePrivada;
    private String rutaLlavePublica;
    private String rutaArchivo;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTabs = new javax.swing.JTabbedPane();
        tabCifrar = new javax.swing.JPanel();
        btnCpubKey = new javax.swing.JButton();
        lblCpubKeyPath = new javax.swing.JLabel();
        btnCAbrir = new javax.swing.JButton();
        lblCArchivoPath = new javax.swing.JLabel();
        lblCinfo = new javax.swing.JLabel();
        btnCifrar = new javax.swing.JButton();
        tabDescifrar = new javax.swing.JPanel();
        btnDprivKey = new javax.swing.JButton();
        lblDprivKeyPath = new javax.swing.JLabel();
        btnDAbrir = new javax.swing.JButton();
        lblDArchivoPath = new javax.swing.JLabel();
        lblDinfo1 = new javax.swing.JLabel();
        btnDescifrar = new javax.swing.JButton();
        tabLlaves = new javax.swing.JPanel();
        btnGenerarPar = new javax.swing.JButton();
        lblInfoGenerarLlaves = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTabs.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        panelTabs.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N

        btnCpubKey.setText("Abrir llave pública");
        btnCpubKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCpubKeyActionPerformed(evt);
            }
        });

        lblCpubKeyPath.setText("Ningún archivo seleccionado...");

        btnCAbrir.setText("Abrir archivo");
        btnCAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAbrirActionPerformed(evt);
            }
        });

        lblCArchivoPath.setText("Ningún archivo seleccionado...");

        lblCinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCinfo.setText("Recuerda obtener la llave pública de la otra persona desde su website");

        btnCifrar.setText("CIFRAR");
        btnCifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCifrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabCifrarLayout = new javax.swing.GroupLayout(tabCifrar);
        tabCifrar.setLayout(tabCifrarLayout);
        tabCifrarLayout.setHorizontalGroup(
            tabCifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCifrarLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(tabCifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCpubKey, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCpubKeyPath)
                    .addComponent(lblCArchivoPath))
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCifrarLayout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(btnCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
            .addGroup(tabCifrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabCifrarLayout.setVerticalGroup(
            tabCifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCifrarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tabCifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCpubKey)
                    .addComponent(lblCpubKeyPath))
                .addGap(20, 20, 20)
                .addGroup(tabCifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCAbrir)
                    .addComponent(lblCArchivoPath))
                .addGap(18, 18, 18)
                .addComponent(btnCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(lblCinfo)
                .addGap(19, 19, 19))
        );

        panelTabs.addTab("Cifrar", tabCifrar);

        btnDprivKey.setText("Abrir llave privada");
        btnDprivKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDprivKeyActionPerformed(evt);
            }
        });

        lblDprivKeyPath.setText("Ningún archivo seleccionado...");

        btnDAbrir.setText("Abrir archivo");
        btnDAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDAbrirActionPerformed(evt);
            }
        });

        lblDArchivoPath.setText("Ningún archivo seleccionado...");

        lblDinfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDinfo1.setText("Recuerda darle tu llave pública a la otra persona desde tu website");

        btnDescifrar.setText("DESCIFRAR");
        btnDescifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescifrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabDescifrarLayout = new javax.swing.GroupLayout(tabDescifrar);
        tabDescifrar.setLayout(tabDescifrarLayout);
        tabDescifrarLayout.setHorizontalGroup(
            tabDescifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDescifrarLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(tabDescifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDprivKey, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabDescifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDprivKeyPath)
                    .addComponent(lblDArchivoPath))
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabDescifrarLayout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(btnDescifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
            .addGroup(tabDescifrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDinfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabDescifrarLayout.setVerticalGroup(
            tabDescifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDescifrarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tabDescifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDprivKey)
                    .addComponent(lblDprivKeyPath))
                .addGap(20, 20, 20)
                .addGroup(tabDescifrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDAbrir)
                    .addComponent(lblDArchivoPath))
                .addGap(18, 18, 18)
                .addComponent(btnDescifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(lblDinfo1)
                .addGap(35, 35, 35))
        );

        panelTabs.addTab("Descifrar", tabDescifrar);

        btnGenerarPar.setText("Generar par de llaves");
        btnGenerarPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarParActionPerformed(evt);
            }
        });

        lblInfoGenerarLlaves.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoGenerarLlaves.setText("Recuerda utilizar siempre las llaves correspondientes al momento de cifrar y descifrar");

        javax.swing.GroupLayout tabLlavesLayout = new javax.swing.GroupLayout(tabLlaves);
        tabLlaves.setLayout(tabLlavesLayout);
        tabLlavesLayout.setHorizontalGroup(
            tabLlavesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabLlavesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoGenerarLlaves, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabLlavesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerarPar, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabLlavesLayout.setVerticalGroup(
            tabLlavesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabLlavesLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(btnGenerarPar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblInfoGenerarLlaves)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        panelTabs.addTab("Llaves", tabLlaves);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarParActionPerformed
        RSA rsa = new RSA();
        rsa.generarLLaves();
        lblInfoGenerarLlaves.setText("Llaves generadas exitosamente");
    }//GEN-LAST:event_btnGenerarParActionPerformed

    private void btnCpubKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCpubKeyActionPerformed
        abrirArchivo((byte) 1);
        if (rutaLlavePublica != null) {
            Archivo archivo = new Archivo(rutaLlavePublica);
            lblCpubKeyPath.setText(rutaLlavePublica);
            llavePublica = (PublicKey) archivo.leerLlave();
        } else {
            JOptionPane.showMessageDialog(null, "Archivo no válido");
        }
    }//GEN-LAST:event_btnCpubKeyActionPerformed

    private void btnCAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAbrirActionPerformed
        abrirArchivo((byte) 2);
        if (rutaArchivo != null) {
            lblCArchivoPath.setText(rutaArchivo);
        } else {
            JOptionPane.showMessageDialog(null, "Archivo no válido");
        }
    }//GEN-LAST:event_btnCAbrirActionPerformed

    private void btnDescifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescifrarActionPerformed
        RSA rsa = new RSA();
        Archivo archivo = new Archivo(rutaArchivo);
        byte[] descifrado;
        descifrado = rsa.decifrarLLavePrivada(archivo.getBytes(),llavePrivada);
        String a = new String(descifrado, StandardCharsets.UTF_8);
        archivo.saveInfo("descifrado.txt", a);
        
        lblCinfo.setText("Informacion descifrada exitosamente");
    }//GEN-LAST:event_btnDescifrarActionPerformed

    private void btnCifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCifrarActionPerformed
        RSA rsa = new RSA();
        Archivo archivo = new Archivo(rutaArchivo);
        String informacion = archivo.getInfo();
        byte[] cifrado;
        cifrado = rsa.cifrarLLavePublica(informacion.getBytes(), llavePublica);
        String a = new String(cifrado, StandardCharsets.UTF_8);
        archivo.saveBytes("cifrado.txt", cifrado);
        
        lblCinfo.setText("Informacion cifrada exitosamente");
        
    }//GEN-LAST:event_btnCifrarActionPerformed

    private void btnDprivKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDprivKeyActionPerformed
        abrirArchivo((byte) 0);
        if (rutaLlavePrivada != null) {
            Archivo archivo = new Archivo(rutaLlavePrivada);
            lblDprivKeyPath.setText(rutaLlavePrivada);
            llavePrivada = (PrivateKey) archivo.leerLlave();
        } else {
            JOptionPane.showMessageDialog(null, "Archivo no válido");
        }
    }//GEN-LAST:event_btnDprivKeyActionPerformed

    private void btnDAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDAbrirActionPerformed
        abrirArchivo((byte) 2);
        if (rutaArchivo != null) {
            lblCArchivoPath.setText(rutaArchivo);
        } else {
            JOptionPane.showMessageDialog(null, "Archivo no válido");
        }
    }//GEN-LAST:event_btnDAbrirActionPerformed

    private void abrirArchivo(byte opcion) {
        JFileChooser file = new JFileChooser();
        file.showOpenDialog(this);
        File abre = file.getSelectedFile();
        switch (opcion) {
            case 0:
                rutaLlavePrivada = abre != null ? abre.getAbsolutePath() : null;
                break;
            case 1:
                rutaLlavePublica = abre != null ? abre.getAbsolutePath() : null;
                break;
            case 2:
                rutaArchivo = abre != null ? abre.getAbsolutePath() : null;
                break;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCAbrir;
    private javax.swing.JButton btnCifrar;
    private javax.swing.JButton btnCpubKey;
    private javax.swing.JButton btnDAbrir;
    private javax.swing.JButton btnDescifrar;
    private javax.swing.JButton btnDprivKey;
    private javax.swing.JButton btnGenerarPar;
    private javax.swing.JLabel lblCArchivoPath;
    private javax.swing.JLabel lblCinfo;
    private javax.swing.JLabel lblCpubKeyPath;
    private javax.swing.JLabel lblDArchivoPath;
    private javax.swing.JLabel lblDinfo1;
    private javax.swing.JLabel lblDprivKeyPath;
    private javax.swing.JLabel lblInfoGenerarLlaves;
    private javax.swing.JTabbedPane panelTabs;
    private javax.swing.JPanel tabCifrar;
    private javax.swing.JPanel tabDescifrar;
    private javax.swing.JPanel tabLlaves;
    // End of variables declaration//GEN-END:variables
}
